-- MySQL Script generated by MySQL Workbench
-- Чт 23 мар 2017 18:51:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_notes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_notes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_notes` DEFAULT CHARACTER SET utf8 ;
USE `db_notes` ;

-- -----------------------------------------------------
-- Table `db_notes`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_notes`.`notes` (
  `id_note` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `text` BLOB NOT NULL,
  `date_of_creation` DATETIME NOT NULL,
  `date_of_removal` DATETIME NULL,
  PRIMARY KEY (`id_note`))
ENGINE = InnoDB;

USE `db_notes`;

DELIMITER $$
USE `db_notes`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db_notes`.`notes_BEFORE_INSERT` BEFORE INSERT ON `notes` FOR EACH ROW
BEGIN
	#SET @sum = @sum + NEW.id_note;
    SET NEW.date_of_creation = now();

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
